services:
  easy-proxies:
    build: .
    image: easy-proxies:local
    container_name: easy-proxies
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - "127.0.0.1:2323:2323"
      - "127.0.0.1:9091:9091"
    volumes:
      - ./config.yaml:/etc/easy-proxies/config.yaml
      - ./nodes.txt:/etc/easy-proxies/nodes.txt
      - ./logs:/app/logs

networks:
  1panel-network:
    external: true
